# Generated by Django 5.1 on 2024-08-19 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_product_on_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='image2',
            field=models.ImageField(default='Image/None/Noimg.jpg', upload_to='Images/products/', verbose_name='照片'),
        ),
        migrations.AddField(
            model_name='product',
            name='image3',
            field=models.ImageField(default='Image/None/Noimg.jpg', upload_to='Images/products/', verbose_name='照片'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_index',
            field=models.ImageField(default='Image/None/Noimg.jpg', upload_to='Images/products/', verbose_name='照片'),
        ),
    ]
