# Generated by Django 5.1 on 2024-08-19 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_experience_description_experience_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='seat_image',
            field=models.ImageField(default='Image/None/Noimg.jpg', upload_to='Images/activities/', verbose_name='座位表'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='image',
            field=models.ImageField(default='Image/None/Noimg.jpg', upload_to='Images/experiences/', verbose_name='圖片'),
        ),
    ]
