# Generated by Django 5.1 on 2024-08-20 03:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_activity_seat_image_alter_experience_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tickets_order', models.JSONField(blank=True, default=list, verbose_name='票券訂單')),
                ('products_order', models.JSONField(blank=True, default=list, verbose_name='商品訂單')),
                ('order_info', models.JSONField(blank=True, default=list, verbose_name='訂單資料')),
                ('order_state', models.CharField(choices=[('unpaid', '未付款'), ('undelivered', '未出貨'), ('finished', '已完成'), ('problem', '問題單')], default='unpaid', max_length=100, verbose_name='訂單狀態')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image3',
        ),
        migrations.AlterField(
            model_name='product',
            name='state_tag',
            field=models.CharField(blank=True, choices=[('on_discount', '特價中'), ('not_sell', '缺貨中'), ('sold_out', '完售'), ('new', '新上市')], help_text='字樣會顯示在圖片上', max_length=100, verbose_name='商品標籤'),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Images/products/')),
                ('is_index', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.product')),
            ],
        ),
    ]
