# Generated by Django 5.1 on 2024-08-20 03:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_order_remove_product_image2_remove_product_image3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_2',
            field=models.ImageField(default='Image/None/Noimg.jpg', upload_to='Images/products/', verbose_name='商品照2'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_3',
            field=models.ImageField(default='Image/None/Noimg.jpg', upload_to='Images/products/', verbose_name='商品照3'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_4',
            field=models.ImageField(default='Image/None/Noimg.jpg', upload_to='Images/products/', verbose_name='商品照4'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_5',
            field=models.ImageField(default='Image/None/Noimg.jpg', upload_to='Images/products/', verbose_name='商品照5'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_index',
            field=models.ImageField(default='Image/None/Noimg.jpg', upload_to='Images/products/', verbose_name='商品照1(兼列表展示照)'),
        ),
        migrations.CreateModel(
            name='AlbumImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Images/albums/')),
                ('is_index', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.album')),
            ],
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
