# Generated by Django 5.1 on 2024-08-20 09:32

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='活動/演出標題')),
                ('date', models.DateField(verbose_name='日期')),
                ('place', models.CharField(max_length=100, verbose_name='場地')),
                ('price_type', models.CharField(max_length=100, verbose_name='票價（例：200/300/500）')),
                ('poster', models.ImageField(default='Image/None/Noimg.jpg', upload_to='Images/activities/', verbose_name='海報圖')),
                ('description', tinymce.models.HTMLField(blank=True, verbose_name='活動介紹')),
                ('program', models.JSONField(default=list, verbose_name='演出內容（曲目）')),
                ('ticket', models.JSONField(default=list, verbose_name='票種清單')),
                ('seat_image', models.ImageField(default='Image/None/Noimg.jpg', upload_to='Images/activities/', verbose_name='座位表')),
            ],
            options={
                'verbose_name': '活動',
                'verbose_name_plural': '活動列表',
            },
        ),
    ]
