# Generated by Django 5.1 on 2024-09-17 05:16

import django.core.files.storage
import django.db.models.deletion
import shortuuidfield.fields
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500, verbose_name='活動/演出標題')),
                ('date', models.DateTimeField(verbose_name='日期時間')),
                ('price_type', models.CharField(max_length=100, verbose_name='所有票價（例：200/300/500）')),
                ('poster', models.ImageField(default='Image/None/Noimg.jpg', upload_to='Images/activities/', verbose_name='海報圖')),
                ('description', tinymce.models.HTMLField(blank=True, verbose_name='活動介紹')),
                ('ticket_system_url', models.CharField(blank=True, max_length=1000, null=True, verbose_name='外部售票系統網址')),
                ('seat_image', models.ImageField(default='Image/None/Noimg.jpg', upload_to='Images/activities/', verbose_name='座位表')),
                ('on_sell', models.BooleanField(default=True)),
                ('excel_file', models.FileField(blank=True, null=True, upload_to='Excel_files', verbose_name='Excel 檔案')),
            ],
            options={
                'verbose_name': '活動',
                'verbose_name_plural': '活動列表',
            },
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('小型場地', '小型場地（總座位數＜300，座位區塊3塊以內）'), ('中小型場地', '中小型場地（總座位數介於300～500，座位區塊6塊以內）'), ('中型場地', '中型場地（總座位數介於500-1200，座位區塊6塊以內）'), ('中大型場地', '中大型場地（總座位數介於1200-2000，座位區塊8塊以內）')], max_length=100)),
                ('name', models.CharField(max_length=300)),
                ('total_seats', models.IntegerField(blank=True)),
                ('address', models.CharField(max_length=500)),
                ('traffic_info', tinymce.models.HTMLField(blank=True, verbose_name='交通資訊')),
                ('map_url', models.CharField(blank=True, max_length=1000)),
                ('official_seat_image', models.ImageField(default='Image/None/Noimg.jpg', upload_to='Images/articles/')),
            ],
        ),
        migrations.CreateModel(
            name='Zone2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(blank=True, max_length=100, null=True, verbose_name='區域名稱')),
                ('row', models.CharField(blank=True, max_length=10, null=True, verbose_name='排數名稱')),
                ('start', models.IntegerField(blank=True, null=True, verbose_name='起始座位號')),
                ('end', models.IntegerField(blank=True, null=True, verbose_name='結束座位號')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='票價')),
                ('excel_file', models.FileField(blank=True, null=True, upload_to=django.core.files.storage.FileSystemStorage(location='/media/excel_files'), verbose_name='Excel 檔案')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='姓名')),
                ('title', models.CharField(blank=True, max_length=500, verbose_name='職稱、腳色')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player', to='activity.event', verbose_name='演出活動')),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='曲目名稱')),
                ('composer', models.CharField(blank=True, max_length=500, verbose_name='作曲家')),
                ('arranger', models.CharField(blank=True, max_length=500, verbose_name='編曲家')),
                ('lyricist', models.CharField(blank=True, max_length=500, verbose_name='作詞家')),
                ('performer', models.CharField(blank=True, max_length=500, verbose_name='協奏者')),
                ('description', models.TextField(blank=True, verbose_name='其他註解')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program', to='activity.event', verbose_name='演出內容')),
            ],
        ),
        migrations.CreateModel(
            name='TicketDiscountCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='例：團員優惠', max_length=100, verbose_name='折扣碼名稱')),
                ('code', models.CharField(help_text='例：MEMBERROCK', max_length=100, verbose_name='折扣碼')),
                ('discount', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='折扣比例，請直接寫小數，例：0.8')),
                ('description', models.CharField(max_length=200, verbose_name='備註＆說明')),
                ('is_valid', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_discount_code', to='activity.event')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='activity.venue', verbose_name='場地'),
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='票種')),
                ('eng_name', models.CharField(max_length=50, verbose_name='票種英文簡稱')),
                ('area', models.CharField(blank=True, choices=[('A', 'A前左'), ('B', 'B前中'), ('C', 'C前右'), ('D', 'D中左'), ('E', 'E中中'), ('F', 'F中右'), ('G', 'G後左'), ('H', 'H後中'), ('J', 'J後右')], max_length=50, null=True, verbose_name='區域相對位置')),
                ('color', models.CharField(choices=[('#FF5151', '紅'), ('#BE77FF', '紫'), ('#9AFF02', '淺綠'), ('#84C1FF', '淺藍'), ('#F9F900', '黃'), ('#FFAF60', '橘'), ('#4F9D9D', '青'), ('#00A600', '深綠'), ('#0073E3', '深藍'), ('#844200', '深棕'), ('#ADADAD', '灰(非賣票)')], max_length=10, verbose_name='座位圖顯示顏色')),
                ('price', models.IntegerField(help_text='可一次指定此區所有票的票價', verbose_name='區域票價')),
                ('remain', models.IntegerField(blank=True, null=True, verbose_name='剩餘票數')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='票券說明（下拉式顯示）')),
                ('help_words', models.CharField(blank=True, help_text='票券說明（直接顯示）', max_length=500, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zone', to='activity.event', verbose_name='對應的演出名稱')),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_num', models.CharField(max_length=10, verbose_name='座位號碼')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='票價')),
                ('area', models.CharField(blank=True, max_length=10, null=True, verbose_name='座位號碼')),
                ('color', models.CharField(blank=True, choices=[('#FF5151', '紅'), ('#BE˙˙FF', '紫'), ('#9AFF02', '淺綠'), ('#84C1FF', '淺藍'), ('#F9F900', '黃'), ('#FFAF60', '橘'), ('#4F9D9D', '青'), ('#00A600', '深綠'), ('#0073E3', '深藍'), ('#844200', '深棕'), ('#ADADAD', '灰(非賣票)')], max_length=10, verbose_name='座位圖顯示顏色')),
                ('is_chair', models.BooleanField(default=False, verbose_name='輪椅席')),
                ('is_sold', models.BooleanField(default=False, verbose_name='已售出')),
                ('not_sell', models.BooleanField(default=False, verbose_name='非賣票')),
                ('event_id', models.CharField(blank=True, editable=False, max_length=20, null=True)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat', to='activity.zone', verbose_name='區域')),
            ],
            options={
                'ordering': ['seat_num'],
            },
        ),
        migrations.CreateModel(
            name='Seat2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(max_length=10)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat2', to='activity.zone2')),
            ],
        ),
        migrations.CreateModel(
            name='ZoneForNumberRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='票種')),
                ('eng_name', models.CharField(max_length=50, verbose_name='票種英文簡稱')),
                ('area', models.CharField(blank=True, choices=[('A', 'A前左'), ('B', 'B前中'), ('C', 'C前右'), ('D', 'D中左'), ('E', 'E中中'), ('F', 'F中右'), ('G', 'G後左'), ('H', 'H後中'), ('J', 'J後右')], help_text='票券上僅會顯示「A區」', max_length=50, null=True, verbose_name='分區')),
                ('color', models.CharField(choices=[('#FF5151', '紅'), ('#BE77FF', '紫'), ('#9AFF02', '淺綠'), ('#84C1FF', '淺藍'), ('#F9F900', '黃'), ('#FFAF60', '橘'), ('#4F9D9D', '青'), ('#00A600', '深綠'), ('#0073E3', '深藍'), ('#844200', '深棕'), ('#ADADAD', '灰(非賣票)')], max_length=10, verbose_name='座位圖顯示顏色')),
                ('price', models.IntegerField(help_text='下方可指定單一票的票價', verbose_name='區域票價')),
                ('remain', models.IntegerField(blank=True, null=True, verbose_name='總數')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='票券說明（下拉式顯示）')),
                ('help_words', models.CharField(blank=True, help_text='票券說明（直接顯示）', max_length=500, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zoneForNumberRow', to='activity.event', verbose_name='對應的演出名稱')),
            ],
        ),
        migrations.CreateModel(
            name='SeatForNumberRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_num', models.CharField(choices=[('01', '第01排'), ('02', '第02排'), ('03', '第03排'), ('04', '第04排'), ('05', '第05排'), ('06', '第06排'), ('07', '第07排'), ('08', '第08排'), ('09', '第09排'), ('10', '第10排'), ('11', '第11排'), ('12', '第12排'), ('13', '第13排'), ('14', '第14排'), ('15', '第15排'), ('16', '第16排'), ('17', '第17排'), ('18', '第18排'), ('19', '第19排'), ('20', '第20排'), ('21', '第21排'), ('22', '第22排'), ('23', '第23排'), ('24', '第24排'), ('25', '第25排'), ('26', '第26排'), ('27', '第27排'), ('28', '第28排'), ('29', '第29排')], max_length=10, verbose_name='排數')),
                ('seat_num', models.CharField(max_length=10, verbose_name='座位號碼')),
                ('area', models.CharField(blank=True, max_length=10, null=True, verbose_name='座位號碼')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='票價')),
                ('color', models.CharField(blank=True, choices=[('#FF5151', '紅'), ('#BE˙˙FF', '紫'), ('#9AFF02', '淺綠'), ('#84C1FF', '淺藍'), ('#F9F900', '黃'), ('#FFAF60', '橘'), ('#4F9D9D', '青'), ('#00A600', '深綠'), ('#0073E3', '深藍'), ('#844200', '深棕'), ('#ADADAD', '灰(非賣票)')], max_length=10, verbose_name='座位圖顯示顏色')),
                ('is_chair', models.BooleanField(default=False, verbose_name='輪椅席')),
                ('is_sold', models.BooleanField(default=False, verbose_name='已售出')),
                ('not_sell', models.BooleanField(default=False, verbose_name='非賣票')),
                ('event_id', models.CharField(blank=True, editable=False, max_length=20, null=True)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat', to='activity.zonefornumberrow', verbose_name='區域')),
            ],
            options={
                'ordering': ['row_num'],
            },
        ),
    ]
