# Generated by Django 5.1 on 2024-08-23 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='on_sell',
            field=models.BooleanField(default=True),
        ),
    ]
