# Generated by Django 5.1 on 2024-09-23 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='is_sold',
            field=models.CharField(choices=[('on_sell', '未售出'), ('sold', '已售出'), ('padding', '保留中')], default='on_sell', max_length=10, verbose_name='已售出'),
        ),
        migrations.AlterField(
            model_name='seatfornumberrow',
            name='is_sold',
            field=models.CharField(choices=[('on_sell', '未售出'), ('sold', '已售出'), ('padding', '保留中')], default='on_sell', max_length=10, verbose_name='已售出'),
        ),
    ]
