# Generated by Django 5.1 on 2024-09-24 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_alter_seat_is_sold_alter_seatfornumberrow_is_sold'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seat',
            old_name='is_sold',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='seatfornumberrow',
            old_name='is_sold',
            new_name='status',
        ),
    ]
