# Generated by Django 5.1 on 2024-08-23 03:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_activity_on_sell'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
