# Generated by Django 5.1 on 2024-09-25 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_rename_is_sold_seat_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='on_sell',
            field=models.BooleanField(default=True, verbose_name='售票中'),
        ),
    ]
