# Generated by Django 5.1 on 2024-08-23 04:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_alter_activity_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=100, primary_key=True, serialize=False),
        ),
    ]
