# Generated by Django 5.1 on 2024-08-24 09:13

import shortuuidfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0004_alter_activity_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='id',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22, primary_key=True, serialize=False),
        ),
    ]
