# Generated by Django 5.1 on 2024-08-24 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0005_alter_activity_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='曲目名稱')),
                ('composer', models.CharField(blank=True, max_length=500, verbose_name='作曲家')),
                ('arranger', models.CharField(blank=True, max_length=500, verbose_name='編曲家')),
                ('lyricist', models.CharField(blank=True, max_length=500, verbose_name='作詞家')),
                ('performer', models.CharField(blank=True, max_length=500, verbose_name='協奏者')),
                ('description', models.TextField(blank=True, verbose_name='其他註解')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='activity.activity', verbose_name='演出內容')),
            ],
        ),
    ]
