# Generated by Django 5.1 on 2024-08-24 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0006_program'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='program',
        ),
    ]
