# Generated by Django 5.1 on 2024-08-31 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0007_remove_activity_program'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Activity',
            new_name='Event',
        ),
    ]
