# Generated by Django 5.1 on 2024-08-31 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0008_rename_activity_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('total_seats', models.IntegerField()),
                ('address', models.CharField(max_length=500)),
                ('traffic_info', models.TextField()),
                ('map_url', models.CharField(max_length=1000)),
                ('official_seat_image', models.ImageField(default='Image/None/Noimg.jpg', upload_to='Images/articles/')),
            ],
        ),
        migrations.RemoveField(
            model_name='event',
            name='ticket',
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(verbose_name='日期時間'),
        ),
        migrations.AlterField(
            model_name='event',
            name='place',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='場地'),
        ),
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='例：團員優惠', max_length=100, verbose_name='折扣碼名稱')),
                ('code', models.CharField(help_text='例：MEMBERROCK', max_length=100, verbose_name='折扣碼')),
                ('discount', models.CharField(max_length=50, verbose_name='折扣比例')),
                ('description', models.CharField(max_length=200, verbose_name='備註＆說明')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_code', to='activity.event')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='activity.venue', verbose_name='預設場地清單'),
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('eng_name', models.CharField(max_length=100)),
                ('color', models.CharField(choices=[('#FF0000', '紅'), ('#00FF00', '綠'), ('#0000FF', '藍'), ('#FFFF00', '黃'), ('#808080', '灰')], max_length=10)),
                ('price', models.IntegerField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='activity.event')),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_num', models.CharField(max_length=10)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='activity.zone')),
            ],
        ),
    ]
