# Generated by Django 5.1 on 2024-08-31 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0009_venue_remove_event_ticket_alter_event_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='activity',
        ),
        migrations.AddField(
            model_name='program',
            name='event',
            field=models.ForeignKey(default='aVjPS48D6qkYg2s5i2hKHc', on_delete=django.db.models.deletion.CASCADE, related_name='program', to='activity.event', verbose_name='演出內容'),
            preserve_default=False,
        ),
    ]
