# Generated by Django 5.1 on 2024-09-01 03:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0010_remove_program_activity_program_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='place',
        ),
        migrations.AlterField(
            model_name='event',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='activity.venue', verbose_name='場地'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat', to='activity.zone'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zone', to='activity.event'),
        ),
    ]
