# Generated by Django 5.1 on 2024-09-01 03:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0011_remove_event_place_alter_event_venue_alter_seat_zone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='姓名')),
                ('title', models.CharField(blank=True, max_length=500, verbose_name='職稱、腳色')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player', to='activity.event', verbose_name='演出活動')),
            ],
        ),
    ]
