# Generated by Django 5.1 on 2024-09-01 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0012_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
