# Generated by Django 5.1 on 2024-09-01 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0013_zone_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='help_words',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
