# Generated by Django 5.1 on 2024-09-03 05:07

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0014_zone_help_words'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='traffic_info',
            field=tinymce.models.HTMLField(blank=True, verbose_name='交通資訊'),
        ),
    ]
