# Generated by Django 5.1 on 2024-09-03 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0015_alter_venue_traffic_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='area',
            field=models.CharField(blank=True, help_text='例：普通票A區、普通票B區', max_length=50, null=True, verbose_name='座位區域'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='color',
            field=models.CharField(choices=[('#FF0000', '紅'), ('#00FF00', '綠'), ('#0000FF', '藍'), ('#FFFF00', '黃'), ('#808080', '灰')], max_length=10, verbose_name='座位圖顯示顏色'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='票券說明（下拉式顯示）'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='eng_name',
            field=models.CharField(max_length=50, verbose_name='票種英文簡稱'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zone', to='activity.event', verbose_name='對應的演出名稱'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='help_words',
            field=models.CharField(blank=True, help_text='票券說明（直接顯示）', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='zone',
            name='name',
            field=models.CharField(max_length=50, verbose_name='票種'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='price',
            field=models.IntegerField(verbose_name='票價'),
        ),
    ]
