# Generated by Django 5.1 on 2024-09-05 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0019_venue_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='ticket_system_url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='size',
            field=models.CharField(choices=[('小型場地', '小型場地（總座位數＜300，座位區塊3塊以內）'), ('中小型場地', '中小型場地（總座位數介於300～500，座位區塊6塊以內）'), ('中型場地', '中型場地（總座位數介於500-1200，座位區塊6塊以內）'), ('中大型場地', '中大型場地（總座位數介於1200-2000，座位區塊8塊以內）')], max_length=100),
        ),
    ]
