# Generated by Django 5.1 on 2024-09-05 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0020_event_ticket_system_url_alter_venue_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='price',
            field=models.IntegerField(blank=True, default='0', verbose_name='票價'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='ticket_system_url',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='外部售票系統網址'),
        ),
        migrations.CreateModel(
            name='Seats2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.IntegerField(verbose_name='票價')),
                ('start', models.IntegerField(verbose_name='結束座位號')),
                ('price', models.IntegerField(verbose_name='票價')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat2', to='activity.zone', verbose_name='區域')),
            ],
        ),
    ]
