# Generated by Django 5.1 on 2024-09-05 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0021_seat_price_alter_event_ticket_system_url_seats2'),
    ]

    operations = [
        migrations.AddField(
            model_name='seats2',
            name='seat_num',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='座位號碼'),
        ),
    ]
