# Generated by Django 5.1 on 2024-09-05 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0022_seats2_seat_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zone2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=100, verbose_name='區域名稱')),
                ('row', models.CharField(max_length=10, verbose_name='排數名稱')),
                ('start', models.IntegerField(verbose_name='起始座位號')),
                ('end', models.IntegerField(verbose_name='結束座位號')),
                ('price', models.IntegerField(verbose_name='票價')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zone2', to='activity.event', verbose_name='對應的演出名稱')),
            ],
        ),
        migrations.CreateModel(
            name='Seat2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(max_length=10)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat2', to='activity.zone2')),
            ],
        ),
        migrations.DeleteModel(
            name='Seats2',
        ),
    ]
