# Generated by Django 5.1 on 2024-09-05 05:32

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0023_zone2_seat2_delete_seats2'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='excel_file',
            field=models.FileField(blank=True, null=True, upload_to=django.core.files.storage.FileSystemStorage(location='/media/excel_files'), verbose_name='Excel 檔案'),
        ),
        migrations.AlterField(
            model_name='zone2',
            name='price',
            field=models.IntegerField(blank=True, verbose_name='票價'),
        ),
    ]
