# Generated by Django 5.1 on 2024-09-05 05:39

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0024_event_excel_file_alter_zone2_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone2',
            name='excel_file',
            field=models.FileField(blank=True, null=True, upload_to=django.core.files.storage.FileSystemStorage(location='/media/excel_files'), verbose_name='Excel 檔案'),
        ),
    ]
