# Generated by Django 5.1 on 2024-09-05 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0025_zone2_excel_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='color',
            field=models.CharField(choices=[('#FF0000', '紅'), ('#00FF00', '綠'), ('#0000FF', '藍'), ('#FFFF00', '黃'), ('#808080', '灰')], default='default', max_length=10, verbose_name='座位圖顯示顏色'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='excel_file',
            field=models.FileField(blank=True, null=True, upload_to='Excel_files', verbose_name='Excel 檔案'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='is_sold',
            field=models.BooleanField(default=False, editable=False, verbose_name='已售出'),
        ),
        migrations.AlterField(
            model_name='zone2',
            name='area',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='區域名稱'),
        ),
        migrations.AlterField(
            model_name='zone2',
            name='end',
            field=models.IntegerField(blank=True, null=True, verbose_name='結束座位號'),
        ),
        migrations.AlterField(
            model_name='zone2',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='票價'),
        ),
        migrations.AlterField(
            model_name='zone2',
            name='row',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='排數名稱'),
        ),
        migrations.AlterField(
            model_name='zone2',
            name='start',
            field=models.IntegerField(blank=True, null=True, verbose_name='起始座位號'),
        ),
    ]
