# Generated by Django 5.1 on 2024-09-05 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0026_seat_color_alter_event_excel_file_alter_seat_is_sold_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='on_sell',
            field=models.BooleanField(default=False, verbose_name='非賣票'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='color',
            field=models.CharField(blank=True, choices=[('#FF5151', '紅'), ('#BE˙˙FF', '紫'), ('#9AFF02', '淺綠'), ('#84C1FF', '淺藍'), ('#F9F900', '黃'), ('#FFAF60', '橘'), ('#4F9D9D', '青'), ('#00A600', '深綠'), ('#0073E3', '深藍'), ('#844200', '深棕'), ('#ADADAD', '灰(非賣票)')], max_length=10, verbose_name='座位圖顯示顏色'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='color',
            field=models.CharField(choices=[('#FF5151', '紅'), ('#BE77FF', '紫'), ('#9AFF02', '淺綠'), ('#84C1FF', '淺藍'), ('#F9F900', '黃'), ('#FFAF60', '橘'), ('#4F9D9D', '青'), ('#00A600', '深綠'), ('#0073E3', '深藍'), ('#844200', '深棕'), ('#ADADAD', '灰(非賣票)')], max_length=10, verbose_name='座位圖顯示顏色'),
        ),
    ]
