# Generated by Django 5.1 on 2024-09-05 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0027_seat_on_sell_alter_seat_color_alter_zone_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seat',
            old_name='on_sell',
            new_name='not_sell',
        ),
    ]
