# Generated by Django 5.1 on 2024-09-05 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0028_rename_on_sell_seat_not_sell'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='票價'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='price',
            field=models.IntegerField(help_text='下方可指定單一票的票價', verbose_name='區域票價'),
        ),
    ]
