# Generated by Django 5.1 on 2024-09-06 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0029_alter_seat_price_alter_zone_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seat',
            options={'ordering': ['seat_num']},
        ),
    ]
