# Generated by Django 5.1 on 2024-09-06 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0030_alter_seat_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zone',
            name='area',
            field=models.CharField(blank=True, choices=[('A', 'A前左'), ('B', 'B前中'), ('C', 'C前右'), ('D', 'D中左'), ('E', 'E中中'), ('F', 'F中右'), ('G', 'G後左'), ('H', 'H後中'), ('I', 'I後右')], help_text='例：普通票A區、普通票B區', max_length=50, null=True, verbose_name='區域相對位置'),
        ),
    ]
