# Generated by Django 5.1 on 2024-09-06 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0031_alter_zone_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zone2',
            name='event',
        ),
        migrations.CreateModel(
            name='ZoneForNumberRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='票種')),
                ('eng_name', models.CharField(max_length=50, verbose_name='票種英文簡稱')),
                ('area', models.CharField(blank=True, choices=[('A', 'A前左'), ('B', 'B前中'), ('C', 'C前右'), ('D', 'D中左'), ('E', 'E中中'), ('F', 'F中右'), ('G', 'G後左'), ('H', 'H後中'), ('I', 'I後右')], help_text='票券上僅會顯示「A區」', max_length=50, null=True, verbose_name='分區')),
                ('color', models.CharField(choices=[('#FF5151', '紅'), ('#BE77FF', '紫'), ('#9AFF02', '淺綠'), ('#84C1FF', '淺藍'), ('#F9F900', '黃'), ('#FFAF60', '橘'), ('#4F9D9D', '青'), ('#00A600', '深綠'), ('#0073E3', '深藍'), ('#844200', '深棕'), ('#ADADAD', '灰(非賣票)')], max_length=10, verbose_name='座位圖顯示顏色')),
                ('price', models.IntegerField(help_text='下方可指定單一票的票價', verbose_name='區域票價')),
                ('total', models.IntegerField(blank=True, null=True, verbose_name='總數')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='票券說明（下拉式顯示）')),
                ('help_words', models.CharField(blank=True, help_text='票券說明（直接顯示）', max_length=500, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zoneForNumberRow', to='activity.event', verbose_name='對應的演出名稱')),
            ],
        ),
        migrations.CreateModel(
            name='SeatForNuberRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_num', models.CharField(choices=[('01', '第01排'), ('02', '第02排'), ('03', '第03排'), ('04', '第04排'), ('05', '第05排'), ('06', '第06排'), ('07', '第07排'), ('08', '第08排'), ('09', '第09排'), ('10', '第10排'), ('11', '第11排'), ('12', '第12排'), ('13', '第13排'), ('14', '第14排'), ('15', '第15排'), ('16', '第16排'), ('17', '第17排'), ('18', '第18排'), ('19', '第19排'), ('20', '第20排'), ('21', '第21排'), ('22', '第22排'), ('23', '第23排'), ('24', '第24排'), ('25', '第25排'), ('26', '第26排'), ('27', '第27排'), ('28', '第28排'), ('29', '第29排')], max_length=10, verbose_name='排數')),
                ('seat_num', models.CharField(max_length=10, verbose_name='座位號碼')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='票價')),
                ('color', models.CharField(blank=True, choices=[('#FF5151', '紅'), ('#BE˙˙FF', '紫'), ('#9AFF02', '淺綠'), ('#84C1FF', '淺藍'), ('#F9F900', '黃'), ('#FFAF60', '橘'), ('#4F9D9D', '青'), ('#00A600', '深綠'), ('#0073E3', '深藍'), ('#844200', '深棕'), ('#ADADAD', '灰(非賣票)')], max_length=10, verbose_name='座位圖顯示顏色')),
                ('is_chair', models.BooleanField(default=False, verbose_name='輪椅席')),
                ('is_sold', models.BooleanField(default=False, editable=False, verbose_name='已售出')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat', to='activity.zonefornumberrow', verbose_name='區域')),
            ],
            options={
                'ordering': ['seat_num'],
            },
        ),
    ]
