# Generated by Django 5.1 on 2024-09-06 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0032_remove_zone2_event_zonefornumberrow_seatfornuberrow'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SeatForNuberRow',
            new_name='SeatForNumberRow',
        ),
    ]
