# Generated by Django 5.1 on 2024-09-06 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0033_rename_seatfornuberrow_seatfornumberrow'),
    ]

    operations = [
        migrations.AddField(
            model_name='seatfornumberrow',
            name='not_sell',
            field=models.BooleanField(default=False, verbose_name='非賣票'),
        ),
    ]
