# Generated by Django 5.1 on 2024-09-07 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0034_seatfornumberrow_not_sell'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seatfornumberrow',
            options={'ordering': ['row_num']},
        ),
        migrations.AlterField(
            model_name='seat',
            name='is_sold',
            field=models.BooleanField(default=False, verbose_name='已售出'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='area',
            field=models.CharField(blank=True, choices=[('A', 'A前左'), ('B', 'B前中'), ('C', 'C前右'), ('D', 'D中左'), ('E', 'E中中'), ('F', 'F中右'), ('G', 'G後左'), ('H', 'H後中'), ('J', 'J後右')], help_text='例：普通票A區、普通票B區', max_length=50, null=True, verbose_name='區域相對位置'),
        ),
        migrations.AlterField(
            model_name='zonefornumberrow',
            name='area',
            field=models.CharField(blank=True, choices=[('A', 'A前左'), ('B', 'B前中'), ('C', 'C前右'), ('D', 'D中左'), ('E', 'E中中'), ('F', 'F中右'), ('G', 'G後左'), ('H', 'H後中'), ('J', 'J後右')], help_text='票券上僅會顯示「A區」', max_length=50, null=True, verbose_name='分區'),
        ),
    ]
