# Generated by Django 5.1 on 2024-09-07 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0035_alter_seatfornumberrow_options_alter_seat_is_sold_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='area',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='座位號碼'),
        ),
        migrations.AddField(
            model_name='seatfornumberrow',
            name='area',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='座位號碼'),
        ),
    ]
