# Generated by Django 5.1 on 2024-09-09 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0036_seat_area_seatfornumberrow_area'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zone',
            old_name='total',
            new_name='remain',
        ),
    ]
