# Generated by Django 5.1 on 2024-09-09 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0037_rename_total_zone_remain'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zonefornumberrow',
            old_name='total',
            new_name='remain',
        ),
    ]
