# Generated by Django 5.1 on 2024-09-10 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0038_rename_total_zonefornumberrow_remain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seatfornumberrow',
            name='is_sold',
            field=models.BooleanField(default=False, verbose_name='已售出'),
        ),
    ]
