# Generated by Django 5.1 on 2024-09-10 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0039_alter_seatfornumberrow_is_sold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountcode',
            name='discount',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='折扣比例，請直接寫小數，例：0.8'),
        ),
    ]
