# Generated by Django 5.1 on 2024-09-10 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0040_alter_discountcode_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountcode',
            name='is_valid',
            field=models.BooleanField(default=False),
        ),
    ]
