# Generated by Django 5.1 on 2024-09-10 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0041_discountcode_is_valid'),
        ('shopping', '0031_alter_orderitem_order'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DiscountCode',
            new_name='TicketDiscountCode',
        ),
    ]
