# Generated by Django 5.1 on 2024-09-11 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0042_rename_discountcode_ticketdiscountcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='price_type',
            field=models.CharField(max_length=100, verbose_name='所有票價（例：200/300/500）'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='area',
            field=models.CharField(blank=True, choices=[('A', 'A前左'), ('B', 'B前中'), ('C', 'C前右'), ('D', 'D中左'), ('E', 'E中中'), ('F', 'F中右'), ('G', 'G後左'), ('H', 'H後中'), ('J', 'J後右')], max_length=50, null=True, verbose_name='區域相對位置'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='price',
            field=models.IntegerField(help_text='可一次指定此區所有票的票價', verbose_name='區域票價'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='remain',
            field=models.IntegerField(blank=True, null=True, verbose_name='剩餘票數'),
        ),
    ]
