# Generated by Django 5.1 on 2024-09-12 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0043_alter_event_price_type_alter_zone_area_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='event_id',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ticketdiscountcode',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_discount_code', to='activity.event'),
        ),
    ]
