# Generated by Django 5.1 on 2024-09-12 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0044_seat_event_id_alter_ticketdiscountcode_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='seatfornumberrow',
            name='event_id',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True),
        ),
    ]
