# Generated by Django 5.1 on 2024-09-17 05:16

import django.db.models.deletion
import shortuuidfield.fields
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=1000, verbose_name='相簿名稱')),
                ('date', models.DateField(verbose_name='日期')),
                ('description', tinymce.models.HTMLField(blank=True, null=True, verbose_name='相簿介紹')),
                ('indexImage', models.ImageField(default='Image/None/Noimg.jpg', upload_to='Images/albums/', verbose_name='相簿封面照')),
            ],
            options={
                'verbose_name': '相簿',
                'verbose_name_plural': '相簿列表',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='文章標題')),
                ('date', models.DateField(verbose_name='日期')),
                ('content', tinymce.models.HTMLField(verbose_name='文章內容')),
                ('article_img', models.ImageField(default='Image/None/Noimg.jpg', upload_to='Images/articles/', verbose_name='文章代表圖片')),
                ('status', models.CharField(choices=[('已發佈', '已發佈'), ('草稿', '草稿'), ('下架封存', '下架封存')], default='草稿', max_length=50, verbose_name='發布狀態')),
                ('tags_input', models.CharField(blank=True, max_length=300, null=True, verbose_name='Hashtag 標記')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章列表',
            },
        ),
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='指揮姓名')),
                ('description', tinymce.models.HTMLField(blank=True, null=True, verbose_name='指揮簡介')),
                ('experiences', tinymce.models.HTMLField(blank=True, null=True, verbose_name='指揮經歷')),
                ('image', models.ImageField(default='Image/None/Noimg.jpg', upload_to='Images/teachers/', verbose_name='照片')),
            ],
            options={
                'verbose_name': '指揮',
                'verbose_name_plural': '指揮列表',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True, verbose_name='姓名')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='電話')),
                ('email', models.EmailField(blank=True, max_length=20, null=True, verbose_name='email')),
                ('category', models.CharField(blank=True, max_length=20, null=True, verbose_name='問題種類')),
                ('title', models.CharField(blank=True, max_length=20, null=True, verbose_name='標題')),
                ('content', models.TextField(blank=True, null=True, verbose_name='內容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立日期')),
                ('reply', models.TextField(blank=True, null=True)),
                ('replied', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='顯示範例：113年2月', verbose_name='日期')),
                ('experience', models.TextField(verbose_name='經歷標題')),
                ('description', tinymce.models.HTMLField(blank=True, null=True, verbose_name='經歷細節介紹')),
                ('image', models.ImageField(default='Image/None/Noimg.jpg', upload_to='Images/experiences/', verbose_name='圖片')),
            ],
            options={
                'verbose_name': '經歷',
                'verbose_name_plural': '經歷列表',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='IndexStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='封面故事標題')),
                ('date', models.DateField(verbose_name='日期')),
                ('place', models.CharField(blank=True, max_length=100, null=True, verbose_name='場地')),
                ('btn_text', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述（不超過10個字）')),
                ('image', models.ImageField(default='Image/None/Noimg.jpg', upload_to='Images/index_stories/', verbose_name='圖片')),
                ('url', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name': '封面故事（會在網頁上方跑馬燈）',
                'verbose_name_plural': '封面故事列表',
            },
        ),
        migrations.CreateModel(
            name='Introduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='更新日期')),
                ('description', tinymce.models.HTMLField(blank=True, null=True, verbose_name='介紹內容')),
                ('indexImage', models.ImageField(default='Image/None/Noimg.jpg', upload_to='Images/intro/', verbose_name='團照')),
                ('image_2', models.ImageField(default='Image/None/Noimg.jpg', upload_to='Images/intro/', verbose_name='LOGO')),
            ],
            options={
                'verbose_name': '樂團介紹',
                'verbose_name_plural': '樂團介紹',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(blank=True, max_length=500, null=True, verbose_name='組別')),
                ('name', models.CharField(max_length=500, verbose_name='老師姓名')),
                ('description', models.TextField(blank=True, verbose_name='老師簡歷')),
                ('image', models.ImageField(default='Image/None/Noimg.jpg', upload_to='Images/teachers/', verbose_name='照片')),
            ],
            options={
                'verbose_name': '分組老師',
                'verbose_name_plural': '老師列表',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='標題')),
                ('date', models.DateField(verbose_name='日期')),
                ('performer', models.CharField(max_length=100, verbose_name='演出者')),
                ('place', models.CharField(max_length=100, verbose_name='演出場地')),
                ('description', models.TextField(blank=True, null=True, verbose_name='演出內容敘述')),
                ('url', models.CharField(max_length=500, verbose_name='youtube網址')),
                ('embed_url', models.CharField(blank=True, max_length=1000, null=True, verbose_name='youtube內嵌網址(請點選youtube分享)')),
                ('image', models.ImageField(default='Image/None/Noimg.jpg', upload_to='Images/videos/', verbose_name='封面照')),
            ],
            options={
                'verbose_name': '影片',
                'verbose_name_plural': '影片列表',
            },
        ),
        migrations.CreateModel(
            name='HomeContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articles', models.ManyToManyField(blank=True, related_name='home_contents', to='information.article')),
                ('events', models.ManyToManyField(blank=True, related_name='home_contents', to='activity.event')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22, primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, upload_to='Images/albums/', verbose_name='照片')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='照片描述')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='information.album', verbose_name='相簿')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='articles', to='information.tag'),
        ),
    ]
