# Generated by Django 5.1 on 2024-09-30 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0002_delete_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
