# Generated by Django 5.1 on 2024-08-19 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0016_rename_products_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='on_discount',
            field=models.BooleanField(default=False),
        ),
    ]
