# Generated by Django 5.1 on 2024-08-19 04:15
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0018_remove_product_image_product_image2_product_image3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(verbose_name='商品敘述'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_price',
            field=models.IntegerField(verbose_name='特價價格'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image2',
            field=models.ImageField(default='Image/None/Noimg.jpg', upload_to='Images/products/', verbose_name='商品照2'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image3',
            field=models.ImageField(default='Image/None/Noimg.jpg', upload_to='Images/products/', verbose_name='商品照3'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_index',
            field=models.ImageField(default='Image/None/Noimg.jpg', upload_to='Images/products/', verbose_name='商品照(兼列表展示照)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='on_discount',
            field=models.BooleanField(default=False, help_text='勾選後，顯示特價價格', verbose_name='優惠中'),
        ),
        migrations.AlterField(
            model_name='product',
            name='on_sell',
            field=models.BooleanField(default=True, help_text='若下架該商品，取消勾選', verbose_name='販售中'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(verbose_name='原始價格'),
        ),
        migrations.AlterField(
            model_name='product',
            name='state_tag',
            field=models.CharField(blank=True, help_text='例：特價中、缺貨、新上架', max_length=100, verbose_name='商品狀態'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=500, verbose_name='商品名稱'),
        ),
    ]
