# Generated by Django 5.1 on 2024-08-19 04:20

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0019_alter_article_content_alter_product_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='活動介紹'),
        ),
        migrations.AlterField(
            model_name='album',
            name='date',
            field=models.DateField(verbose_name='日期'),
        ),
        migrations.AlterField(
            model_name='album',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='相簿介紹'),
        ),
        migrations.AlterField(
            model_name='album',
            name='indexImage',
            field=models.ImageField(default='Image/None/Noimg.jpg', upload_to='Images/albums/', verbose_name='相簿封面照'),
        ),
        migrations.AlterField(
            model_name='album',
            name='title',
            field=models.CharField(max_length=1000, verbose_name='相簿名稱'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='文章內容'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='商品敘述'),
        ),
    ]
