# Generated by Django 5.1 on 2024-08-24 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0024_customtag_customtaggedarticle_alter_article_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customtag',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
