# Generated by Django 5.1 on 2024-08-20 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0024_product_image_2_product_image_3_product_image_4_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='albumimage',
            old_name='product',
            new_name='album',
        ),
    ]
