# Generated by Django 5.1 on 2024-08-20 04:44

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0025_rename_product_albumimage_album'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=tinymce.models.HTMLField(blank=True, verbose_name='文章內容'),
        ),
    ]
