# Generated by Django 5.1 on 2024-08-24 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0025_alter_customtag_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customtaggedarticle',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='article',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='customtaggedarticle',
            name='content_type',
        ),
        migrations.DeleteModel(
            name='CustomTag',
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.CharField(blank=True, help_text='請以逗號分隔標籤', max_length=100),
        ),
        migrations.DeleteModel(
            name='CustomTaggedArticle',
        ),
    ]
