# Generated by Django 5.1 on 2024-08-24 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0026_remove_customtaggedarticle_tag_remove_article_tags_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='tags_input',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.RemoveField(
            model_name='article',
            name='tags',
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='articles', to='information.tag'),
        ),
    ]
