# Generated by Django 5.1 on 2024-08-20 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0026_alter_article_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products', models.JSONField()),
                ('need_deliver_paid', models.BooleanField(default=True)),
                ('total', models.IntegerField()),
            ],
        ),
    ]
