# Generated by Django 5.1 on 2024-08-20 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0027_productcart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductCart',
        ),
    ]
