# Generated by Django 5.1 on 2024-08-24 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0027_tag_article_tags_input_remove_article_tags_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='tag_name',
            new_name='name',
        ),
    ]
