# Generated by Django 5.1 on 2024-08-24 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0028_rename_tag_name_tag_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='video',
            name='tags',
        ),
        migrations.AddField(
            model_name='album',
            name='tags_input',
            field=models.CharField(blank=True, help_text='請以逗號分隔標籤', max_length=300),
        ),
        migrations.AddField(
            model_name='video',
            name='tags_input',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
