# Generated by Django 5.1 on 2024-08-24 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0029_remove_album_tags_remove_video_tags_album_tags_input_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='tags_input',
        ),
    ]
