# Generated by Django 5.1 on 2024-08-24 07:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0030_remove_video_tags_input'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.RemoveField(
            model_name='album',
            name='tags_input',
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='Images/albums/', verbose_name='照片')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='照片描述')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='information.album', verbose_name='相簿')),
            ],
        ),
        migrations.DeleteModel(
            name='AlbumImage',
        ),
    ]
