# Generated by Django 5.1 on 2024-08-24 09:09

import shortuuidfield.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0031_image_remove_album_tags_input_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='date',
            field=models.CharField(help_text='格式：113年8月', max_length=100, verbose_name='日期'),
        ),
        migrations.AlterField(
            model_name='video',
            name='id',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, default=uuid.uuid4, editable=False, max_length=22, primary_key=True, serialize=False),
        ),
    ]
