# Generated by Django 5.1 on 2024-08-24 09:11

import shortuuidfield.fields
import uuid
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0032_alter_experience_date_alter_video_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='id',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, default=uuid.uuid4, editable=False, max_length=22, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='id',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, default=uuid.uuid4, editable=False, max_length=22, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='photo',
            name='id',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, default=uuid.uuid4, editable=False, max_length=22, primary_key=True, serialize=False),
        ),
    ]
