# Generated by Django 5.1 on 2024-08-26 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0033_alter_album_id_alter_article_id_alter_photo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='date',
            field=models.DateField(help_text='顯示範例：2024年2月', verbose_name='日期'),
        ),
    ]
