# Generated by Django 5.1 on 2024-08-26 08:34

import django.db.models.deletion
import shortuuidfield.fields
import tinymce.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0033_alter_album_id_alter_article_id_alter_photo_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='指揮姓名')),
                ('description', tinymce.models.HTMLField(blank=True, verbose_name='指揮簡介')),
                ('experiences', tinymce.models.HTMLField(blank=True, verbose_name='指揮經歷')),
                ('image', models.ImageField(default='Image/None/Noimg.jpg', upload_to='Images/teachers/', verbose_name='照片')),
            ],
            options={
                'verbose_name': '指揮',
                'verbose_name_plural': '指揮列表',
            },
        ),
        migrations.CreateModel(
            name='Introduction',
            fields=[
                ('id', shortuuidfield.fields.ShortUUIDField(blank=True, default=uuid.uuid4, editable=False, max_length=22, primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='更新日期')),
                ('description', tinymce.models.HTMLField(blank=True, verbose_name='介紹內容')),
                ('indexImage', models.ImageField(default='Image/None/Noimg.jpg', upload_to='Images/intro/', verbose_name='相簿封面照')),
            ],
            options={
                'verbose_name': '樂團介紹',
                'verbose_name_plural': '樂團介紹',
            },
        ),
        migrations.AlterField(
            model_name='experience',
            name='date',
            field=models.DateField(help_text='顯示範例：113年2月', verbose_name='日期'),
        ),
        migrations.AddField(
            model_name='photo',
            name='introduction',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='information.introduction', verbose_name='樂團介紹'),
            preserve_default=False,
        ),
    ]
