# Generated by Django 5.1 on 2024-08-26 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0034_alter_experience_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='指揮姓名')),
                ('description', models.TextField(blank=True, verbose_name='指揮簡介')),
                ('experiences', models.TextField(blank=True, verbose_name='指揮經歷')),
                ('image', models.ImageField(default='Image/None/Noimg.jpg', upload_to='Images/teachers/', verbose_name='照片')),
            ],
            options={
                'verbose_name': '指揮',
                'verbose_name_plural': '指揮列表',
            },
        ),
        migrations.AlterField(
            model_name='experience',
            name='date',
            field=models.DateField(help_text='顯示範例：113年2月', verbose_name='日期'),
        ),
    ]
