# Generated by Django 5.1 on 2024-08-26 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0035_remove_photo_image_remove_photo_introduction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='introduction',
            name='image_2',
            field=models.ImageField(default='Image/None/Noimg.jpg', upload_to='Images/intro/', verbose_name='LOGO'),
        ),
        migrations.AlterField(
            model_name='introduction',
            name='indexImage',
            field=models.ImageField(default='Image/None/Noimg.jpg', upload_to='Images/intro/', verbose_name='團照'),
        ),
    ]
