# Generated by Django 5.1 on 2024-08-27 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0036_introduction_image_2_alter_introduction_indeximage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='albumImage',
            new_name='image',
        ),
    ]
