# Generated by Django 5.1 on 2024-08-30 02:36

import shortuuidfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0037_rename_albumimage_photo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='id',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22, primary_key=True, serialize=False),
        ),
    ]
