# Generated by Django 5.1 on 2024-08-31 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0040_alter_album_description_alter_article_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='introduction',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
