# Generated by Django 5.1 on 2024-09-02 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0041_alter_introduction_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='tags_input',
        ),
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('已發佈', '已發佈'), ('草稿', '草稿'), ('下架封存', '下架封存')], default='草稿', max_length=50, verbose_name='發布狀態'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
