# Generated by Django 5.1 on 2024-09-02 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0044_alter_tag_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='article',
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='articles', to='information.tag'),
        ),
    ]
