# Generated by Django 5.1 on 2024-09-02 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0045_remove_tag_article_article_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='tags_input',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Hashtag 標記'),
        ),
    ]
