# Generated by Django 5.1 on 2024-09-02 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0014_zone_help_words'),
        ('information', '0046_article_tags_input'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articles', models.ManyToManyField(blank=True, related_name='home_contents', to='information.article')),
                ('events', models.ManyToManyField(blank=True, related_name='home_contents', to='activity.event')),
            ],
        ),
    ]
