# Generated by Django 5.1 on 2024-09-13 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0048_contact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='contact',
            name='replied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contact',
            name='reply',
            field=models.TextField(blank=True, null=True),
        ),
    ]
