# Generated by Django 5.1 on 2024-09-18 02:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='姓名')),
                ('email', models.EmailField(max_length=254, verbose_name='電子郵件')),
                ('phone', models.CharField(max_length=20, verbose_name='電話')),
                ('postal_code', models.CharField(max_length=10, verbose_name='郵遞區號')),
                ('address_city', models.CharField(max_length=100, verbose_name='城市')),
                ('address_district', models.CharField(max_length=100, verbose_name='區域')),
                ('address', models.CharField(max_length=1000, verbose_name='詳細地址')),
                ('paid_method', models.CharField(blank=True, choices=[('credit_card', '信用卡'), ('virtual_ATM', 'ATM虛擬帳號'), ('line_pay', 'Line Pay'), ('apple_pay', 'Apple Pay')], max_length=20, verbose_name='付費方式')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='創建時間')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='更新時間')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '顧客',
                'verbose_name_plural': '顧客',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('user', '一般用戶'), ('admin', '管理員')], default='user', max_length=5)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用戶資料',
                'verbose_name_plural': '用戶資料',
            },
        ),
    ]
