# Generated by Django 5.1 on 2024-08-20 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tickets_order', models.JSONField(blank=True, default=list, verbose_name='票券訂單')),
                ('products_order', models.JSONField(blank=True, default=list, verbose_name='商品訂單')),
                ('order_info', models.JSONField(blank=True, default=list, verbose_name='訂單資料')),
                ('order_state', models.CharField(choices=[('unpaid', '未付款'), ('undelivered', '未出貨'), ('finished', '已完成'), ('problem', '問題單')], default='unpaid', max_length=100, verbose_name='訂單狀態')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products', models.JSONField()),
                ('need_deliver_paid', models.BooleanField(default=True)),
                ('total', models.IntegerField()),
            ],
        ),
    ]
