# Generated by Django 5.1 on 2024-08-20 10:08

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='商品名稱')),
                ('price', models.IntegerField(verbose_name='原始價格')),
                ('discount_price', models.IntegerField(verbose_name='特價價格')),
                ('description', tinymce.models.HTMLField(blank=True, verbose_name='商品敘述')),
                ('state_tag', models.CharField(blank=True, choices=[('on_discount', '特價中'), ('not_sell', '缺貨中'), ('sold_out', '完售'), ('new', '新上市')], help_text='字樣會顯示在圖片上', max_length=100, verbose_name='商品標籤')),
                ('on_sell', models.BooleanField(default=True, help_text='若下架該商品，取消勾選', verbose_name='販售中')),
                ('on_discount', models.BooleanField(default=False, help_text='勾選後，顯示特價價格', verbose_name='優惠中')),
                ('image_index', models.ImageField(default='Image/None/Noimg.jpg', upload_to='Images/products/', verbose_name='商品照1(兼列表展示照)')),
                ('image_2', models.ImageField(default='Image/None/Noimg.jpg', upload_to='Images/products/', verbose_name='商品照2')),
                ('image_3', models.ImageField(default='Image/None/Noimg.jpg', upload_to='Images/products/', verbose_name='商品照3')),
                ('image_4', models.ImageField(default='Image/None/Noimg.jpg', upload_to='Images/products/', verbose_name='商品照4')),
                ('image_5', models.ImageField(default='Image/None/Noimg.jpg', upload_to='Images/products/', verbose_name='商品照5')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品列表',
            },
        ),
        migrations.AlterModelOptions(
            name='productcart',
            options={'verbose_name': '購物車', 'verbose_name_plural': '購物車列表'},
        ),
    ]
