# Generated by Django 5.1 on 2024-08-23 04:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_alter_activity_id'),
        ('shopping', '0003_alter_order_id_alter_product_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=100)),
                ('address_city', models.CharField(max_length=100)),
                ('address_district', models.CharField(max_length=100)),
                ('address_street', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_info',
        ),
        migrations.RemoveField(
            model_name='order',
            name='products_order',
        ),
        migrations.RemoveField(
            model_name='order',
            name='tickets_order',
        ),
        migrations.RemoveField(
            model_name='productcart',
            name='need_deliver_paid',
        ),
        migrations.RemoveField(
            model_name='productcart',
            name='total',
        ),
        migrations.AddField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productcart',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('need_deliver_paid', models.BooleanField(default=True)),
                ('total', models.IntegerField()),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shopping.productcart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.product')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.customer', verbose_name='訂購人資料')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='shopping.order')),
                ('products', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='shopping.product', verbose_name='商品訂單')),
                ('tickets', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='activity.activity', verbose_name='票券訂單')),
            ],
        ),
    ]
