# Generated by Django 5.1 on 2024-09-18 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0003_alter_order_total_amount'),
        ('user', '0002_customer_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.customer', verbose_name='訂購人資料'),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
