# Generated by Django 5.1 on 2024-08-23 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0005_alter_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='tickets',
        ),
        migrations.RemoveField(
            model_name='productcart',
            name='products',
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='products',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='shopping.productcart', verbose_name='商品訂單'),
        ),
    ]
