# Generated by Django 5.1 on 2024-09-25 08:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0006_remove_cart_customer_order_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='added_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
