# Generated by Django 5.1 on 2024-09-26 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0007_cartitem_added_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='pre_sold_qty',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sold_qty',
        ),
        migrations.AddField(
            model_name='size',
            name='pre_sold_qty',
            field=models.IntegerField(default=0, verbose_name='暫時售出量'),
        ),
        migrations.AddField(
            model_name='size',
            name='quantity',
            field=models.IntegerField(blank=True, null=True, verbose_name='庫存總量'),
        ),
        migrations.AddField(
            model_name='size',
            name='sold_qty',
            field=models.IntegerField(default=0, verbose_name='已售出總量'),
        ),
    ]
