# Generated by Django 5.1 on 2024-08-23 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0007_remove_customer_address_street_customer_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '購物車',
                'verbose_name_plural': '購物車列表',
            },
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shopping.cart'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='products',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='shopping.cart', verbose_name='商品訂單'),
        ),
        migrations.DeleteModel(
            name='ProductCart',
        ),
    ]
