# Generated by Django 5.1 on 2024-09-26 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0008_remove_product_pre_sold_qty_remove_product_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='group',
            field=models.CharField(blank=True, choices=[('單一尺寸', '單一尺寸'), ('大人、成年人', '大人、成年人'), ('小孩', '小孩')], max_length=50, null=True, verbose_name='適用族群'),
        ),
        migrations.AlterField(
            model_name='size',
            name='quantity',
            field=models.IntegerField(default=50, verbose_name='庫存總量'),
        ),
        migrations.AlterField(
            model_name='size',
            name='size',
            field=models.CharField(blank=True, max_length=100, verbose_name='尺寸或顏色'),
        ),
    ]
