# Generated by Django 5.1 on 2024-08-23 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0009_alter_cart_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='total',
            new_name='sum',
        ),
        migrations.AddField(
            model_name='cart',
            name='deliver_paid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart',
            name='final_total',
            field=models.IntegerField(),
            preserve_default=False,
        ),
    ]
