# Generated by Django 5.1 on 2024-08-24 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0011_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_4',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_5',
        ),
    ]
