# Generated by Django 5.1 on 2024-08-30 02:36

import django.db.models.deletion
import shortuuidfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0013_alter_photo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='id',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartItems', to='shopping.cart'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='id',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image_data',
            field=models.ImageField(upload_to='Images/albums/', verbose_name='其他商品照片'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('stationary', '文具'), ('cloth', '服飾（衣服、帽子、襪子）'), ('media', '演出影音')], max_length=500, verbose_name='商品種類'),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_index',
            field=models.ImageField(default='Image/None/Noimg.jpg', upload_to='Images/products/', verbose_name='商品封面照'),
        ),
        migrations.AlterField(
            model_name='product',
            name='state_tag',
            field=models.CharField(blank=True, choices=[('特價中', '特價中'), ('缺貨中', '缺貨中'), ('完售', '完售'), ('新上市', '新上市')], help_text='字樣會顯示在圖片上', max_length=100, verbose_name='商品標籤'),
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='尺寸描述')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='size_list', to='shopping.product', verbose_name='尺寸列表')),
            ],
        ),
    ]
