# Generated by Django 5.1 on 2024-08-30 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0014_alter_cart_id_alter_cartitem_cart_alter_photo_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='size',
            old_name='size',
            new_name='name',
        ),
    ]
