# Generated by Django 5.1 on 2024-08-30 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0015_rename_size_size_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='size',
            old_name='name',
            new_name='product',
        ),
        migrations.AddField(
            model_name='size',
            name='size',
            field=models.CharField(default='default', max_length=100, verbose_name='尺寸'),
            preserve_default=False,
        ),
    ]
