# Generated by Django 5.1 on 2024-08-30 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0016_rename_name_size_product_size_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='size',
            name='group',
            field=models.CharField(blank=True, choices=[('大人、成年人', '大人、成年人'), ('小孩', '小孩')], max_length=50, verbose_name='尺寸'),
        ),
    ]
