# Generated by Django 5.1 on 2024-08-30 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0017_size_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='level',
            field=models.CharField(blank=True, max_length=50, verbose_name='顯示順序'),
        ),
        migrations.AlterField(
            model_name='size',
            name='description',
            field=models.CharField(blank=True, max_length=255, verbose_name='備註，例：尺寸描述'),
        ),
        migrations.AlterField(
            model_name='size',
            name='group',
            field=models.CharField(blank=True, choices=[('大人、成年人', '大人、成年人'), ('小孩', '小孩')], max_length=50, verbose_name='適用族群'),
        ),
        migrations.AlterField(
            model_name='size',
            name='size',
            field=models.CharField(max_length=100, verbose_name='尺寸或顏色'),
        ),
    ]
