# Generated by Django 5.1 on 2024-08-30 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0018_photo_level_alter_size_description_alter_size_group_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image_index',
            new_name='index_image',
        ),
    ]
