# Generated by Django 5.1 on 2024-09-10 03:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0039_alter_seatfornumberrow_is_sold'),
        ('shopping', '0020_alter_product_category_alter_product_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='products',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': '顧客', 'verbose_name_plural': '顧客'},
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_state',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='customer',
        ),
        migrations.AddField(
            model_name='customer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='創建時間'),
        ),
        migrations.AddField(
            model_name='customer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='更新時間'),
        ),
        migrations.AddField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shopping.customer', verbose_name='訂購人資料'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='need_deliver_paid',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('unpaid', '未付款'), ('undelivered', '未出貨'), ('finished', '已完成'), ('problem', '問題單'), ('canceled', '已取消')], default='unpaid', max_length=100, verbose_name='訂單狀態'),
        ),
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orderItem', to='shopping.product', verbose_name='商品'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product_sum',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='qty',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='ticketsV2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='activity.seatfornumberrow', verbose_name='第二類票券訂單'),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(blank=True, null=True, verbose_name='庫存總量'),
        ),
        migrations.AddField(
            model_name='product',
            name='sold_qty',
            field=models.IntegerField(blank=True, null=True, verbose_name='已售出總量'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(max_length=1000, verbose_name='詳細地址'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address_city',
            field=models.CharField(max_length=100, verbose_name='城市'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address_district',
            field=models.CharField(max_length=100, verbose_name='區域'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='電子郵件'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=200, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='paid_method',
            field=models.CharField(blank=True, choices=[('credit_card', '信用卡'), ('virtual_ATM', 'ATM虛擬帳號'), ('line_pay', 'Line Pay'), ('apple_pay', 'Apple Pay')], max_length=20, verbose_name='付費方式'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='電話'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='postal_code',
            field=models.CharField(max_length=10, verbose_name='郵遞區號'),
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
