# Generated by Django 5.1 on 2024-09-10 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0039_alter_seatfornumberrow_is_sold'),
        ('shopping', '0021_remove_cartitem_cart_remove_orderitem_products_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='例：團員優惠', max_length=100, verbose_name='商品折扣碼名稱')),
                ('code', models.CharField(help_text='例：MEMBER', max_length=100, verbose_name='折扣碼')),
                ('discount', models.CharField(max_length=50, verbose_name='折扣比例，請直接寫小數，例：0.8')),
                ('description', models.CharField(max_length=100, verbose_name='備註＆說明')),
            ],
        ),
        migrations.AddField(
            model_name='orderitem',
            name='discount_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='activity.discountcode', verbose_name='票券優惠碼'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='tickets',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='activity.seat', verbose_name='第一類票券訂單'),
        ),
        migrations.AlterField(
            model_name='order',
            name='need_deliver_paid',
            field=models.BooleanField(default=True, verbose_name='要加運費'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.IntegerField(null=True, verbose_name='訂單總金額'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shopping.productcode', verbose_name='商品優惠碼'),
        ),
    ]
