# Generated by Django 5.1 on 2024-09-10 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0040_alter_discountcode_discount'),
        ('shopping', '0026_alter_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='discount_code',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='ticket_discount_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='activity.discountcode'),
        ),
    ]
