# Generated by Django 5.1 on 2024-09-10 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0027_remove_order_discount_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='title',
            new_name='name',
        ),
    ]
