# Generated by Django 5.1 on 2024-09-10 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0028_rename_title_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcode',
            name='is_valid',
            field=models.BooleanField(default=False),
        ),
    ]
