# Generated by Django 5.1 on 2024-09-10 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0029_productcode_is_valid'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcode',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='有效日期'),
        ),
        migrations.AlterField(
            model_name='productcode',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='備註＆說明'),
        ),
        migrations.AlterField(
            model_name='productcode',
            name='is_valid',
            field=models.BooleanField(default=False, verbose_name='開啟優惠碼'),
        ),
    ]
