# Generated by Django 5.1 on 2024-09-10 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0042_rename_discountcode_ticketdiscountcode'),
        ('shopping', '0031_alter_orderitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='size',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='尺寸或顏色'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_code', to='shopping.productcode'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='ticket_discount_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_discount_code', to='activity.ticketdiscountcode'),
        ),
    ]
