# Generated by Django 5.1 on 2024-09-11 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0032_orderitem_size_alter_orderitem_product_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='deliver_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='運費金額'),
        ),
    ]
