# Generated by Django 5.1 on 2024-09-12 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0033_order_deliver_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='deliver_price',
            field=models.IntegerField(blank=True, default=70, null=True, verbose_name='運費金額'),
        ),
    ]
