# Generated by Django 5.1 on 2024-09-13 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0034_alter_order_deliver_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcode',
            options={'verbose_name': '商品優惠碼', 'verbose_name_plural': '商品優惠碼'},
        ),
        migrations.AddField(
            model_name='product',
            name='pre_sold_qty',
            field=models.IntegerField(blank=True, null=True, verbose_name='暫時售出量'),
        ),
    ]
